-- GENERATED by tools/bizhawk_ram.py from ps4disasm/ps4.constants.asm.
-- Do not edit: run the generator instead.
--
-- `addr` is the 68000 address as the disassembly writes it; `off` is
-- that address inside BizHawk's 64K work-RAM domain.
return {
  Game_Mode_Routine = { addr = 0xFFFFEC20, off = 0xEC20, size = 2 },  -- which top-level mode is running
  Window_Index = { addr = 0xFFFFEC90, off = 0xEC90, size = 2 },  -- window currently being drawn
  Saved_Window_Index = { addr = 0xFFFFEC92, off = 0xEC92, size = 2 },
  Windows_Opened_Num = { addr = 0xFFFFEC9A, off = 0xEC9A, size = 1 },  -- how many windows are stacked
  Panel_Num = { addr = 0xFFFFED02, off = 0xED02, size = 1 },  -- cut-in panels resident
  Current_Dialogue_Tree = { addr = 0xFFFFED60, off = 0xED60, size = 4 },
  Joypad_Held = { addr = 0xFFFFEF02, off = 0xEF02, size = 1 },
  Joypad_Pressed = { addr = 0xFFFFEF03, off = 0xEF03, size = 1 },
  Camera_X_Pos_FG = { addr = 0xFFFFEF94, off = 0xEF94, size = 2 },
  Camera_Y_Pos_FG = { addr = 0xFFFFEF90, off = 0xEF90, size = 2 },
  Current_Money = { addr = 0xFFFFF438, off = 0xF438, size = 4 },  -- meseta - the field whose digits wrapped a row high
  Message_Speed = { addr = 0xFFFFF440, off = 0xF440, size = 2 },
}
