"""Generate tools/bizhawk/ram.lua from the disassembly's own RAM equates.

The harness reads game state by address, and an address typed by hand into a
Lua file is an address that silently rots the next time the RAM map moves.
`ps4.constants.asm` is the map the ROM is actually assembled against, so
generate from it and the two cannot disagree.

    python tools/bizhawk_ram.py
"""
import io
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONSTANTS = os.path.join(ROOT, 'ps4disasm', 'ps4.constants.asm')
OUT = os.path.join(ROOT, 'tools', 'bizhawk', 'ram.lua')

# What the walk needs to know about. Keep this list short and purposeful: each
# name here is something a check asserts on or a log line explains a failure
# with, not everything that happens to live in RAM.
WANTED = [
    ('Game_Mode_Routine', 2, 'which top-level mode is running'),
    ('Window_Index', 2, 'window currently being drawn'),
    ('Saved_Window_Index', 2, ''),
    ('Windows_Opened_Num', 1, 'how many windows are stacked'),
    ('Panel_Num', 1, 'cut-in panels resident'),
    ('Current_Dialogue_Tree', 4, ''),
    ('Joypad_Held', 1, ''),
    ('Joypad_Pressed', 1, ''),
    ('Camera_X_Pos_FG', 2, ''),
    ('Camera_Y_Pos_FG', 2, ''),
    ('Current_Money', 4, 'meseta - the field whose digits wrapped a row high'),
    ('Message_Speed', 2, ''),
]


def main():
    src = io.open(CONSTANTS, encoding='utf-8', errors='replace').read()
    found, missing = [], []
    for name, size, note in WANTED:
        m = re.search(r'^%s\s*=\s*ramaddr\(\$([0-9A-Fa-f]+)\)' % re.escape(name),
                      src, re.M)
        if not m:
            missing.append(name)
            continue
        addr = int(m.group(1), 16)
        # The Genesis core exposes work RAM as a 64K domain; $FFxxxx addresses
        # index it by their low word.
        found.append((name, addr, addr & 0xFFFF, size, note))
    if missing:
        raise SystemExit('not in ps4.constants.asm: ' + ', '.join(missing))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    out = ['-- GENERATED by tools/bizhawk_ram.py from ps4disasm/ps4.constants.asm.',
           '-- Do not edit: run the generator instead.',
           '--',
           '-- `addr` is the 68000 address as the disassembly writes it; `off` is',
           '-- that address inside BizHawk\'s 64K work-RAM domain.',
           'return {']
    for name, addr, off, size, note in found:
        out.append('  %s = { addr = 0x%06X, off = 0x%04X, size = %d },%s'
                   % (name, addr, off, size, ('  -- ' + note) if note else ''))
    out.append('}')
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    print('wrote %s with %d symbols' % (os.path.relpath(OUT, ROOT), len(found)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
