"""Port the item descriptions from script_translated.json into the disassembly.

The 8x8 name tables reach the source build as prerendered strips (menustrip)
or regenerated byte tables (fieldstrings), but the item descriptions are not a
name table -- they are the only prose in that bank, and the disassembly still
carries the US localisers' text for them as plain `dc.b` strings.  This writes
ours over both copies.

The strings stay ASCII: script/charset.asm maps them, and it has a period, a
comma, an apostrophe and a hyphen, so nothing here needs the drawn punctuation
that the legacy JP-ROM path installs for the same table.

InventoryDescriptions and InventoryDescriptions2 hold identical text and differ
only in their terminator, $FF against $FE. Both are rewritten from the same
source so they cannot drift apart.

    python tools/itemdesc.py            report only
    python tools/itemdesc.py --write    rewrite ps4.asm
"""
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASM = os.path.join(ROOT, 'ps4disasm', 'ps4.asm')
SCRIPT = os.path.join(ROOT, 'work', 'script_translated.json')
SEGMENT = '01:003'
LINE_CELLS = 24          # measured from the window, not from the data:
                         # WinGroup_Menu $35/$46 is the box these draw in,
                         # and 24 cells is what it actually shows.  The old
                         # 28 was 'the widest line the JP original uses',
                         # which let 31 lines through that clip in play.


def entries():
    """[(en, us)] for the 160 description rows, in table order."""
    d = json.load(io.open(SCRIPT, encoding='utf-8'))
    es = d['entries'] if isinstance(d, dict) else d
    rows = [e for e in es if (e.get('segment') or '') == SEGMENT]
    rows.sort(key=lambda e: int(e['id'].rsplit('#', 1)[1]))
    return [((e.get('en') or '').strip(), (e.get('us') or '').strip())
            for e in rows]


LABEL = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*:')


def find(lines, label):
    for i, ln in enumerate(lines):
        if ln.startswith(label + ':'):
            return i
    raise SystemExit('%s not found in ps4.asm' % label)


def end_of(lines, a):
    """The next label after `a`, which is where this table's body stops.

    Not simply the next table: a couple of short unrelated strings sit between
    InventoryDescriptions and InventoryDescriptions2, and overwriting them
    would take the shop's "equip" with them.
    """
    for i in range(a + 1, len(lines)):
        if LABEL.match(lines[i]):
            return i
    raise SystemExit('no label follows line %d' % a)


def comments(lines, a, b):
    """The `; ITEMNAME` headings already in the block, in order."""
    out = []
    for ln in lines[a:b]:
        m = re.match(r'^;\s*(\S.*?)\s*$', ln)
        if m:
            out.append(m.group(1))
    return out


def render(text, name, term):
    out = ['', '; ' + name]
    for i, part in enumerate(text.split('{FC}')):
        if i:
            out.append('\tdc.b\t$FC')
        out.append('\tdc.b\t"%s"' % part)
    out.append('\tdc.b\t' + term)
    return out


def rewrite(lines, label, term, rows):
    a = find(lines, label)
    b = end_of(lines, a)
    names = comments(lines, a, b)
    if len(names) != len(rows):
        raise SystemExit('%s has %d item comments for %d rows'
                         % (label, len(names), len(rows)))
    body = []
    for (en, us), name in zip(rows, names):
        body += render(en or us, name, term)
    body.append('')
    # whatever closed the old block (a blank line, an `even`) is kept as-is
    last = max(i for i in range(a, b) if lines[i].strip().startswith('dc.b'))
    tail = lines[last + 1:b]
    while tail and not tail[0].strip():
        tail.pop(0)
    while body and not body[-1].strip():
        body.pop()
    while body and not body[0].strip():
        body.pop(0)
    return lines[:a + 1] + [''] + body + [''] + tail + lines[b:], len(body)


def line_cells(text):
    """Cells a description line occupies in Item > Look: RunText composes it
    with the menu face, so measure in pixels with menuwidth.bin (a plain sum
    of advances, as VWFMenu_DrawString does) rather than counting characters
    against the old fixed-width field.  The same line is also shown by shop
    vendors in the DIALOGUE face (256 px box); see dialogue_over()."""
    import re
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import menustrip
    plain = re.sub(r'\{[^}]*\}', '', text)
    px = sum(menustrip.width[menustrip.code[c]] for c in plain if c in menustrip.code)
    return -(-px // 8)


def dialogue_over(text):
    """Pixels over the shop's dialogue box, or 0."""
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import dialogue_reflow as R
    return max(0, R.px(text) - R.LIMIT)


def main():
    rows = entries()
    blank = [i for i, (en, us) in enumerate(rows) if not en and not us]
    over = [(i, L, line_cells(L)) for i, (en, _) in enumerate(rows)
            for L in en.split('{FC}') if line_cells(L) > LINE_CELLS]
    over += [(i, en, 99) for i, (en, _) in enumerate(rows) if en.count('{FC}') > 1]  # a third line is dropped
    over += [(i, L + '  (shop: %d px over the dialogue box)' % dialogue_over(L), line_cells(L))
             for i, (en, _) in enumerate(rows) for L in en.split('{FC}') if dialogue_over(L)]
    print('%d descriptions, %d translated, %d blank'
          % (len(rows), sum(1 for en, _ in rows if en), len(blank)))
    if over:
        for i, L, n in over:
            print('  row %d line is %d cells: %s' % (i, n, L))
        return 1
    if '--write' not in sys.argv:
        print('(dry run; pass --write to rewrite ps4.asm)')
        return 0

    lines = io.open(ASM, encoding='utf-8', errors='replace').read().split('\n')
    lines, _ = rewrite(lines, 'InventoryDescriptions2', '$FE', rows)
    lines, _ = rewrite(lines, 'InventoryDescriptions', '$FF', rows)
    io.open(ASM, 'w', encoding='utf-8', errors='replace',
            newline='\n').write('\n'.join(lines))
    print('rewrote both description tables in ps4.asm')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
