"""Run the build under BizHawk with the Lua harness and collect what it saw.

    python tools/playtest.py                 # ps4en.bin, default walk
    python tools/playtest.py --rom other.bin
    python tools/playtest.py --timeout 300

Leaves work/playtest/ holding the screenshots, the log the harness wrote, and
a copy of the RAM map the run used, so a run can be read back later without
guessing which build or which addresses produced it.

BizHawk takes one `--lua=`, with no way to hand it arguments, so this writes a
small bootstrap that sets OUT_DIR and then loads the harness.
"""
import argparse
import io
import os
import shutil
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'work', 'playtest')
LUA = os.path.join(ROOT, 'tools', 'bizhawk')
CANDIDATES = [
    os.path.join(os.environ.get('LOCALAPPDATA', ''), 'Microsoft', 'WinGet',
                 'Packages'),
    os.environ.get('ProgramFiles', ''),
    os.path.join(os.environ.get('USERPROFILE', ''), 'BizHawk'),
]


def find_emuhawk():
    override = os.environ.get('EMUHAWK')
    if override and os.path.isfile(override):
        return override
    for root in CANDIDATES:
        if not root or not os.path.isdir(root):
            continue
        for dirpath, _dirs, files in os.walk(root):
            if 'EmuHawk.exe' in files:
                return os.path.join(dirpath, 'EmuHawk.exe')
    raise SystemExit('EmuHawk.exe not found; set EMUHAWK to its full path')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--rom', default=os.path.join(ROOT, 'ps4en.bin'))
    ap.add_argument('--walk', default='harness.lua')
    ap.add_argument('--timeout', type=int, default=420)
    ap.add_argument('--keep', action='store_true',
                    help='do not clear work/playtest first')
    args = ap.parse_args()

    emuhawk = find_emuhawk()
    rom = os.path.abspath(args.rom)
    if not os.path.isfile(rom):
        raise SystemExit('no such ROM: ' + rom)

    if os.path.isdir(OUT) and not args.keep:
        shutil.rmtree(OUT)
    os.makedirs(OUT, exist_ok=True)

    subprocess.run([sys.executable, os.path.join(ROOT, 'tools', 'bizhawk_ram.py')],
                   check=True)
    shutil.copy(os.path.join(LUA, 'ram.lua'), os.path.join(OUT, 'ram.lua'))

    posix_out = OUT.replace('\\', '/')
    boot = os.path.join(OUT, 'bootstrap.lua')
    io.open(boot, 'w', encoding='utf-8', newline='\n').write(
        '-- generated by tools/playtest.py\n'
        'OUT_DIR = "%s"\n'
        'dofile("%s/%s")\n' % (posix_out, LUA.replace('\\', '/'), args.walk))

    # Stage the ROM as .md. BizHawk cannot infer a platform from .bin and puts
    # up a picker dialog, which with no one at the keyboard simply hangs -- the
    # first run of this harness sat on that dialog for its whole timeout and
    # produced nothing. Copying also keeps the exact image beside the shots it
    # produced, so a run can be identified later.
    staged = os.path.join(OUT, 'rom.md')
    shutil.copy(rom, staged)

    print('emuhawk : %s' % emuhawk)
    print('rom     : %s  (staged as rom.md)' % rom)
    print('out     : %s' % OUT)
    started = time.time()
    proc = subprocess.Popen([emuhawk, '--lua=' + boot, staged],
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    try:
        proc.communicate(timeout=args.timeout)
    except subprocess.TimeoutExpired:
        proc.kill()
        print('TIMEOUT after %ds - killed EmuHawk' % args.timeout)
    print('ran for %.0fs' % (time.time() - started))

    log = os.path.join(OUT, 'log.txt')
    if os.path.isfile(log):
        print('\n--- harness log ---')
        sys.stdout.write(io.open(log, encoding='utf-8', errors='replace').read())
    else:
        print('\nno log.txt: the harness did not reach its end')
    shots = sorted(f for f in os.listdir(OUT) if f.endswith('.png'))
    print('\n%d screenshot(s): %s' % (len(shots), ', '.join(shots) or '(none)'))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
