"""Inject the English VWF font, widths and slot map into proofread.html.

Two problems this solves.

The proofreader used to score English against ps4_dialogue.tbl, but that table
is the JAPANESE decoder: it carries the 26 capitals and no lowercase at all, so
every modern line failed with "no mapping". English lives in english.py.

Narration is rendered with the EN ROM's variable-width dialogue font, taken
from the disassembly at vwf/diafont.bin + vwf/diawidth.bin. Those widths are
exact and already include the inter-character gap, so a line's pixel width is
just the sum - no estimating. The glyphs come along too, so the page can draw
each line at true size against the 8px cell grid.

Generated rather than hand-copied so the page cannot drift from the encoder or
the font. Run: python tools/proofsync.py
"""
import io, json, os, sys, base64
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import english
import menustrip
import combonames
import guildnames
import spacemenu
import trpatch8

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, 'ps4disasm', 'vwf', 'diafont.bin')
WIDTH = os.path.join(ROOT, 'ps4disasm', 'vwf', 'diawidth.bin')
# The menu face is a SEPARATE pair. Narration/dialogue use diafont+diawidth;
# menus use menufont+menuwidth, and menuwidth.bin is the same file the ROM
# bincludes at VWFMenu_Widths - so measuring here cannot drift from either the
# prerenderer or the runtime. Mixing the two faces mis-measures by about a
# pixel per character, which is exactly enough to lose a cell boundary.
MFONT = os.path.join(ROOT, 'ps4disasm', 'vwf', 'menufont.bin')
MWIDTH = os.path.join(ROOT, 'ps4disasm', 'vwf', 'menuwidth.bin')
MIDX = os.path.join(ROOT, 'ps4disasm', 'vwf', 'menustripidx.bin')
# strip category -> first strip index, matching menustripbase.bin
STRIP_BASE = {'00:001': 0, '00:002': 160, '00:003': 200, '00:004': 254}

BEGIN = '/* ---------- GENERATED by tools/proofsync.py ---------- */'
END = '/* ---------- end generated ---------- */'

def menu_charmap():
    """Menu charset, taken from tools/menustrip.py so there is one definition.

    Note lowercase lives at 57, not 27: the menu face renders it as small
    capitals. Reading it as 27 measures lowercase against the digits.
    """
    m = {' ': 0}
    for i, c in enumerate('ABCDEFGHIJKLMNOPQRSTUVWXYZ'):
        m[c] = 1 + i
    for i, c in enumerate('0123456789'):
        m[c] = 27 + i
    for i, c in enumerate('abcdefghijklmnopqrstuvwxyz'):
        m[c] = 57 + i
    m['-'] = 0x31; m['!'] = 0x32; m['?'] = 0x33; m[':'] = 0x34
    m['.'] = 0x53; m["'"] = 0x54; m[','] = 0x55
    m['ü'] = 0x57            # dedicated u-diaeresis shared with the runtime
    return m


# Glyph order read off the rendered sheet: space, A-Z, a-z, punctuation,
# then digits. 74-79 are unused. There is no ';' or '(' ')' in this font.
def charmap():
    m = {' ': 0}
    for i, c in enumerate('ABCDEFGHIJKLMNOPQRSTUVWXYZ'):
        m[c] = 1 + i
    for i, c in enumerate('abcdefghijklmnopqrstuvwxyz'):
        m[c] = 27 + i
    for c, i in zip(".',\u00b7:!?", range(53, 60)):
        m[c] = i
    m['-'] = 60
    m['"'] = 61
    m['%'] = 63
    for i, c in enumerate('0123456789'):
        m[c] = 64 + i
    return m


def menu_limits():
    """Every segment the menu VWF composes -> its cell field.

    A value is a cell count, or a list of [from, to, cells] index ranges
    (cells null = uncapped) where one segment mixes roles.  Taken from the
    generators that enforce them - menustrip/combonames/guildnames/spacemenu
    and trpatch8's index split - rather than restated, so a budget change in
    the build shows up in the page on the next sync.
    """
    lim = {}
    for seg, _label, budget, _sym in menustrip.TABLES:
        lim[seg] = budget
    for _sym, seg, _slots, _n, budget in combonames.TABLES:
        lim[seg] = budget
    lim['00:007'] = guildnames.CELLS
    for seg in ('02:001', '02:002', '03:000'):
        lim[seg] = trpatch8.SEGMENT_LIMIT[seg]
    for seg, ranges in trpatch8.INDEX_LIMIT.items():
        lim[seg] = [list(r) for r in ranges]
    # spacemenu's own numbers win for the prompt/name rows it lays out
    lim['00:008'] = [[0, 1, spacemenu.PROMPT_CELLS], [1, 2, None],
                     [2, 8, spacemenu.NAME_CELLS]]
    return dict(sorted(lim.items()))


def build():
    font = open(FONT, 'rb').read()
    widths = open(WIDTH, 'rb').read()
    idx = charmap()
    mface = open(MFONT, 'rb').read()
    mwidth = bytearray(open(MWIDTH, 'rb').read())
    # The prerenderer overrides the space advance for strips only; mirror that
    # here or the page's cell preview charges a full cell for every gap and
    # disagrees with the strips it is supposed to be previewing.
    mwidth[0] = menustrip.SPACE_ADV
    midx = open(MIDX, 'rb').read()
    counts = {'00:001': 160, '00:002': 40, '00:003': 54, '00:004': 54}
    recorded = {seg: [midx[(STRIP_BASE[seg] + i) * 4 + 2] for i in range(n)]
                for seg, n in counts.items()}
    return (f'{BEGIN}\n'
            f'const MENU_IDX = {json.dumps(menu_charmap(), ensure_ascii=False, sort_keys=True)};\n'
            f'const MENU_W = {json.dumps(list(mwidth))};\n'
            f'const MENU_FONT_B64 = "{base64.b64encode(mface).decode()}";\n'
            f'const MENU_CELLS = {json.dumps(recorded)};\n'
            f'const MENU_LIMITS = {json.dumps(menu_limits())};\n'
            f'const EN_SLOTS = {json.dumps(english.SLOTS, sort_keys=True)};\n'
            f'const VWF_IDX = {json.dumps(idx, ensure_ascii=False, sort_keys=True)};\n'
            f'const VWF_W = {json.dumps(list(widths))};\n'
            f'const VWF_FONT_B64 = "{base64.b64encode(font).decode()}";\n'
            f'const VWF_BPG = {len(font) // len(widths)};\n'
            f'const VWF_CELL = 8, VWF_LINE_PX = 256;\n'
            f'{END}')


def main():
    for p in (FONT, WIDTH):
        if not os.path.exists(p):
            print('missing ' + p); return 1
    p = os.path.join(ROOT, 'tools', 'proofread.html')
    s = io.open(p, encoding='utf-8').read()
    block = build()
    if BEGIN in s:
        s = s[:s.index(BEGIN)] + block + s[s.index(END) + len(END):]
    else:
        a = '/* encode -> byte length'
        s = s.replace(a, block + '\n' + a)
    io.open(p, 'w', encoding='utf-8').write(s)
    print(f'proofread.html: {len(english.SLOTS)} slots, '
          f'{len(open(WIDTH,"rb").read())} glyph widths, font embedded')
    return 0


if __name__ == '__main__':
    sys.exit(main())
